### PR TITLE
Enable building for older macOS devices

### PR DESCRIPTION
**Pull request by sseering**
Small change.  ¯\\_(ツ)_/¯

### CODE REVIEW

**Review by 12Marvin98 — APPROVED** [review]
Works on my 2016 Intel MacBook

**Comment by ahasselbring** [comment]
`uname -m` returns `arm64` on my device, but the target is called `aarch64-...`.

**Comment by ahasselbring** [comment]
f1cda00b45171c6b1fd07d90164e618ed6b78709 should handle one part of this PR.

**Comment by 12Marvin98** [comment]
Yes it works, but the LSMinimumSystemVersion in Line 72 is to high. For me 12.6 instead of 13.3 works fine.

**Pull request closed without merging**
